import Head from 'next/head'
import styles from './index.module.css'
import Login from '../components/Login/index'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>登陆</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>
        <Login />
      </main>
      <footer className={styles.footer}>
        Table Export ©2022 Created by LIULIN
      </footer>
    </div>
  )
}
